### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by maleadt**
Update CUDA.jl compat bounds and adapt to some changes.

@thomasfaingnaert Kernels don't compile, but you were already looking into a regression so I take it you have a fix already?

### CODE REVIEW

**Comment by thomasfaingnaert** [comment]
There was only a performance regression, IIRC everything still compiled correctly for 1.6.

**Comment by maleadt** [comment]
Yeah it's the CUDA.jl update that break things, I figured you had updated that dependency too.

**Comment by thomasfaingnaert** [comment]
Pushed a fix for diagonal matrices on 1.6. I'm not that experienced with `UnionAll`s, but isn't the way you were doing it supposed to work? If so, I guess that's a bug in the Julia 1.6 compiler?

I'll have a closer look at the dynamic function invocation issues that occur on 1.7 later.

**Comment by maleadt** [comment]
> Yeah it's the CUDA.jl update that break things, I figured you had updated that dependency too.

Actually it's just the upgrade to Julia 1.7, as CI reveals here.

> I'm not that experienced with UnionAlls, but isn't the way you were doing it supposed to work? If so, I guess that's a bug in the Julia 1.6 compiler?

It should, yes.

> I'll have a closer look at the dynamic function invocation issues that occur on 1.7 later.

It's something to do with indexing into the the result of `iterate` which may be nothing. But changing `subdivide` to what's below triggers a cascade of other failures which I'll have a look at tomorrow:

```
@inline function subdivide(tile::Tile{size, names, T}, tiling_size::Tile{tile_sz, names, T}, idx, count) where {names, T, size, tile_sz}
    iter = iterate(parallellise(tile, tiling_size, idx, count))
    iter === nothing && throw(BoundsError())
    iter[1]
end
```

**Comment by maleadt** [comment]
Fixed the dynamic invocation, but now the code allocates on 1.7 (dynamic memory, which is only meant to be used in error paths). I fear this may be an instance of https://github.com/JuliaLang/julia/issues/41800.

**Pull request merged**
