### PR TITLE
Run Buildkite on Julia 1.5, 1.6-nightly, and nightly

### PR DESCRIPTION
**Pull request by DilumAluthge**
I'm not optimistic that tests will pass on Julia nightly, but we might as well test on it.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Looks like it's out of memory-ing.

@maleadt Should we do `CUDA.reclaim()` at the beginning of the test suite, or something?

**Comment by maleadt** [comment]
> Should we do `CUDA.reclaim()` at the beginning of the test suite, or something?

No, never. That's an internal function which has gotten too much external use... The OOM builds were on cyclops, it's more likely that some user was just occupying all GPUs (the joys of shared infrastructure and no free way to virtualize GPUs).

**Comment by DilumAluthge** [comment]
Oof, this is killing me. My GemmKernels PRs are competing with my BLASBenchmarksGPU PRs.

Could we use CUDA_VISIBLE_DEVICES to make each runner only use a single GPU? E.g. on 1.cyclops we set CUDA_VISIBLE_DEVICES=0, on 2.cyclops we set CUDA_VISIBLE_DEVICES=1, etc?

**Comment by DilumAluthge** [comment]
Cyclops has five GPUs, right? And we have three Buildkite runners ("agents") on Cyclops?

How about we do this:
- 1.cyclops only has access to GPU 0
- 2.cyclops only has access to GPU 1
- 3.cyclops only has access to GPUs 2, 3, and 4

**Comment by maleadt** [comment]
CI is acting up a little too: two systems (!) have died, and there's some heavy users active on `cyclops` right now. Normally it's the runner with the lowest priority, but if no other are available...

**Comment by DilumAluthge** [comment]
Anyway, this PR is good to merge now.

Once 1.6 is released, I'll remove the testing on 1.6-nightly, and we'll only test on 1 and nightly.

**Pull request merged**
