### PR TITLE
Use separate test toml file.

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Out of curiosity, is there a reason you prefer a separate `test/Project.toml` file?

**Comment by maleadt** [comment]
Much easier to do `julia --project=test test/runtests.jl` then.

**Comment by DilumAluthge** [comment]
Should we just (temporarily) tell GemmKernels Buildkite to not use Cyclops?

Is there an ability in Buildkite to say "please don't use 1.cyclops, 2.cyclops, or 3.cyclops"?

**Comment by maleadt** [comment]
cyclops has been removed from CI.

**Comment by DilumAluthge** [comment]
> cyclops has been removed from CI.

Problem solved 😂

**Comment by DilumAluthge** [comment]
Well, not solved, but worked around 😂

**Pull request merged**
