### PR TITLE
Run Buildkite on both Julia 1.5 and Julia 1.6-nightly

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@maleadt Are the test failures on Julia 1.6 due to a bug in GemmKernels.jl or CUDA.jl?

**Comment by thomasfaingnaert** [comment]
CI's using the CUDA.jl version from the manifest, which I'm guessing isn't compatible with 1.6.

**Comment by DilumAluthge** [comment]
Hmmm. Still seems to fail.

**Comment by DilumAluthge** [comment]
Yeah, even when I delete the manifest, CI is still failing on Julia 1.6.

**Comment by thomasfaingnaert** [comment]
The culprit is probably the diagonal test. Let me try something.

**Comment by DilumAluthge** [comment]
That fixed it! Good to merge now?

**Comment by thomasfaingnaert** [comment]
@maleadt Should we keep the Manifest to record the exact versions of dependencies? If so, we should probably add a ManifestUpdater to this repository, too.

**Comment by DilumAluthge** [comment]
If so, we'll need to keep (and update) two different manifests, one for Julia 1.5 and one for Julia 1.6.

**Comment by DilumAluthge** [comment]
@maleadt Can the manifest updater update multiple manifests? We could have e.g. Manifest.1.5.toml and Manifest.1.6.toml.

And then, at the beginning of each Buildkite job, we identify the correct manifest and rename it to Manifest.toml.

(Personally, I don't check manifests into source control because I find them too much trouble to work with. But if we do keep manifests in source control for this package, we'll need multiple.)

**Comment by maleadt** [comment]
Let's just remove the Manifest for now then. I typically do it for reproducibility, as well as to be able to depend on unreleased versions of packages, but we can revisit that when we would need it here.

**Comment by DilumAluthge** [comment]
Good to merge this then?

**Pull request merged**
