### PR TITLE
Tropical mma (WIP)

### PR DESCRIPTION
**Pull request by GiggleLiu**
This is a handwaving version of implementing Tropical BLAS on GPU, to explain what I want to do.

Tropical algebra is normal algebra with
* `+` changed to  `max`
* `*` changeed to `+`

@thomasfaingnaert 
* Since Tropical algebra can not utilize the TensorCore. Do you think implementing `mma` for Tropical numbers will improve the performance comparing with the fallback generic matmul in CUDA?
* I do not know much about CUDA programming. Do you have any example of implementing `mma` from scrach that I can learn from?

Many thanks.

### CODE REVIEW

**Comment by thomasfaingnaert** [comment]
Do you mean WMMA's multiply-accumulate with `mma`? If so, that is not applicable here, since Tensor Cores do not support matrix multiplication with `+` and `max`.

Nevertheless, adding support for tropical numbers in GemmKernels should be able to outperform the generic fallback of CUDA.jl, as the latter does not use tiling techniques or shared memory.

**Comment by GiggleLiu** [comment]
Ok. I want to utilize the tiling and shared memory defined in GemmKernels to accelerate Tropical matmul.
Is it easy to do and is there any code that I can refer?

**Comment by thomasfaingnaert** [comment]
You can start by checking how standard WMMA GEMM is implemented, as tropical numbers will be fairly similar.
Whether or not that is easy depends on how familiar you are with how the GEMM on GPUs is implemented.
If you are new to CUDA programming, that might be a lot of work in and of itself.

**Comment by GiggleLiu** [comment]
I have only limited experience with CUDA programming, but I still want to have a try. Can you provide a link to

> how standard WMMA GEMM is implemented

Thank you!

**Comment by thomasfaingnaert** [comment]
Quick overview of the code path of the example test at https://github.com/thomasfaingnaert/GemmKernels.jl/blob/master/test/matmul.jl#L12-L53:

1. `get_config` is called which determines the layouts, operator, kernel, etc. that is used for the kernel launch. Not all parameters are set explicitly, you may want to print `conf` to inspect them.
2. `GemmKernels.matmul` is called, which redirects to one of the two kernels in `kernel.jl`. You might want to start with `matmul_singlestage` as it is the easiest to understand.
3. The kernel consists of different steps, that each call generic functions such as `Layout.load`, `Operator.mma`, etc. These have some types as parameters, that are used to select the correct implementation using Julia's multiple dispatch. For example, `GLOBAL_A_LAYOUT` is `AlignedColMajor{Float16}`, so https://github.com/thomasfaingnaert/GemmKernels.jl/blob/51c05e28533caaa041bc4705e22ebdf41cefde8c/src/kernel.jl#L66 redirects to https://github.com/thomasfaingnaert/GemmKernels.jl/blob/51c05e28533caaa041bc4705e22ebdf41cefde8c/src/layout.jl#L76-L83.

Also consider checking out the accompanying paper, as it explains the structure of GEMM in more detail.

**Comment by GiggleLiu** [comment]
Thanks for your links. I find the paper especially well written.

As far as I have learnt. What I need to implement is a new `Operator.mma` function. It is returns `A*B + C` with `A`, `B` and `C` fragments of input matrices. A fragment is a small sub-matrix that can fit into the GPU register. Typically, its size is 16x16x16.
However, the only example about writting `mma` is in `CUDA.WMMA`, which calls into the TensorCore directly. Since tropical numbers can not utilize TensorCore, I need to write a kernel function containing a 3 fold unrolled-loop.
But it is not clear to me that how to access the element in the fragment, and how to allocate the return value?

Since the storage of tropical numbers are basically floating point numbers. The loading and tiling are same as regular GEMM. So I do not need to touch this part of code. Right?

**Comment by thomasfaingnaert** [comment]
> Thanks for your links. I find the paper especially well written.
> 
> As far as I have learnt. What I need to implement is a new `Operator.mma` function. It is returns `A*B + C` with `A`, `B` and `C` fragments of input matrices. A fragment is a small sub-matrix that can fit into the GPU register. Typically, its size is 16x16x16.

You will also need to implement `load_{a,b,c}` and `store_d` for your new operator.
The fragment sizes for WMMA are not 16 x 16.
WMMA is a warp-wide operation that calculates e.g. an 16 x 16 x 16 matrix multiplication, but each thread only needs a part of the input and output matrices.
The exact mapping of threads to matrix elements is undefined AFAIK, and depends on GPU architecture, but if you want to mimic WMMA you could check what the mapping is and use it here as well.

> However, the only example about writting `mma` is in `CUDA.WMMA`, which calls into the TensorCore directly. Since tropical numbers can not utilize TensorCore, I need to write a kernel function that containing a 3 fold unrolled-loop and dispatch it to this `mma` function.
> But it is not clear to me that how to access the element in the fragment, and how to allocate the return value?

Allocating return values for the `Operator.load_{a,b,c}` functions etc. can be done using the StaticArrays.jl package, as I have done for the Layout.loads.

> Since the storage of tropical numbers are basically floating point numbers. The loading and tiling are same as regular GEMM. So I do not need to touch this part of code. Right?

If you're referring to kernel.jl, then no, you should not need to adapt anything. But you will need a layout that supports FP64 if you want to use 64-bit tropical numbers, as the current layouts only support FP16 and FP32.

**Comment by maleadt** [comment]
This is part of https://github.com/JuliaGPU/GemmKernels.jl/pull/101

**Pull request closed without merging**
