### PR TITLE
Move to BuildKite.

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Fixes both #54 and #55

**Comment by thomasfaingnaert** [comment]
The coverage information doesn't seem very accurate, possibly because of the aggressive inlining?

**Comment by DilumAluthge** [comment]
Let's try on nightly. Coverage info might be more accurate there.

**Comment by maleadt** [comment]
We currently don't support coverage for GPU device code...

**Comment by DilumAluthge** [comment]
Ooof. That's.... unfortunate :(

Two questions:
1. Is there an issue that I can subscribe to to track the topic of code coverage for GPU device code?
2. In the mean time, can we apply your fix from https://discourse.julialang.org/t/how-to-generate-coverage-for-cuda-functions/43752/2?

**Comment by maleadt** [comment]
Yeah, an example here: https://github.com/JuliaGPU/CUDA.jl/blob/465535069383ce66b137c6c64f188e4b9164ec15/src/mapreduce.jl#L1-L132
Another possibility, what I do in CUDA.jl, is to put all device code in a separate folder and exclude that, https://github.com/JuliaGPU/CUDA.jl/blob/486141a3dcb050cc191681e0de6684f915c51532/codecov.yml#L4

**Comment by maleadt** [comment]
> Is there an issue that I can subscribe to to track the topic of code coverage for GPU device code?

There isn't one yet, feel free to open one on CUDA.jl.

**Comment by DilumAluthge** [comment]
> > Is there an issue that I can subscribe to to track the topic of code coverage for GPU device code?
> 
> There isn't one yet, feel free to open one on CUDA.jl.

https://github.com/JuliaGPU/CUDA.jl/issues/708

**Pull request merged**
